{
 "title": "Otel Trace Log",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"logs\"\n  )\n  |> map(fn: (r) => ({_value: r.host}))\n  |> unique()\n"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "TRACE, DEBUG, INFO, WARN, ERROR, FATAL"
   },
   {
    "name": "trace_id",
    "label": "TraceId",
    "query": "037c422ed19f3d6a625d6259aaeeba5c"
   },
   { "name": "span_id", "label": "SpanId" },
   {
    "name": "service_name",
    "label": "Service",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"logs\"\n  )\n  |> map(fn: (r) => ({_value: r[\"service.name\"]}))\n  |> unique()"
   },
   { "name": "bucket", "query": "default" },
   { "name": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"spans\" and not exists r.parent_span_id\n  )\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\n  |> group()"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"array\"\nimport \"experimental\"\nimport \"experimental/array\"\nimport \"experimental/record\"\nimport \"json\"\nimport \"strings\"\n\nconvert = (r) => {\n  keys = experimental.objectKeys(o: r)\n  tags = keys\n    |> array.filter(fn: (x) => strings.hasPrefix(prefix: \"_tag_\", v: x)) \n    |> array.map(fn: (x) => ({key: strings.trimPrefix(prefix: \"_tag_\", v: x), value: record.get(r: r, key: x, default: \"\")}))\n  return {r with tags: string(v: json.encode(v: tags))}\n}\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"spans\" and r.trace_id == \"${trace_id}\" and (\"${span_id}\" == \"\" or \"${span_id}\" == r.span_id)\n  )\n  |> map(fn: (r) => {\n    prefix = if r._field != \"duration_nano\" and r._field != \"end_time_unix_nano\" then\n      \"_tag_\"\n    else\n      \"\"\n    return {r with _field: prefix + r._field}\n  })\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => convert(r: r))\n  |> map(fn: (r) => {\n    serviceTags = \"[]\"\n    parentSpanID = if exists r.parent_span_id then\n      r.parent_span_id\n    else\n      \"\"\n    return {traceID: r.trace_id, spanID: r.span_id, parentSpanID: parentSpanID, operationName: r.name, serviceName: r[\"service.name\"], startTime: (r.end_time_unix_nano - r.duration_nano) / 1000000, duration: r.duration_nano / 1000000, serviceTags: serviceTags, tags: r.tags}\n  })\n"
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "\nimport \"strings\"\n\nvalueIn = (va, s) => {\n    return if s == \"auto\" then\n      true\n    else\n      contains(\n        value: va,\n        set: strings.split(\n          v: strings.trimRight(\n            v: strings.trimLeft(\n              v: s,\n              cutset: \"{\"),\n            cutset: \"}\"),\n          t: \",\"))\n}\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"logs\"\n  )\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> filter(fn: (r) =>\n    valueIn(va: r[\"host\"], s: \"${host}\")\n  )\n  |> filter(fn: (r) =>\n    valueIn(va: r[\"level\"], s: \"${level}\")\n  )\n  |> filter(fn: (r) =>\n    \"${trace_id}\" == \"\" or \"${trace_id}\" == r[\"trace_id\"]\n  )\n  |> filter(fn: (r) =>\n    \"${span_id}\" == \"\" or \"${span_id}\" == r[\"span_id\"]\n  )\n  |> filter(fn: (r) =>\n    valueIn(va: r[\"service.name\"], s: \"${service_name}\")\n  )\n  |> map(fn: (r) => ({r with _value: r.name}))\n  |> drop(columns: [\"name\", \"_start\", \"_stop\", \"_measurement\"])"
    }
   ]
  }
 ]
}